[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
cobs = "0.2.3"
crc = "3.0"
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode.workspace = true
